version: '3.7'

services:
  tracker:
    build: .
    restart: unless-stopped
    command: daphne -b 0.0.0.0 -p 8000 tracker_project.asgi:application
    env_file:
      ./.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/tracker/"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 10s
    volumes:
      - static:/var/www/static
    depends_on:
      - db

  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/tracker/"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - static:/var/www/static
    ports:
      - "8000:80"
      - "443:443"
    depends_on:
      - tracker

  db:
    image: postgres:12-alpine
    volumes:
      - db_data:/var/lib/postgresql
    environment:
      - POSTGRES_USER=tracker
      - POSTGRES_PASSWORD=deadbeef
      - POSTGRES_DB=donations

volumes:
  static:
  db_data:
